name: generate pacman game

on:
  schedule:
    - cron: "0 0 * * *"  
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Push to output branch
        run: |
          echo "✅ Setting up Git config"
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

          echo "📁 Copy hasil generate ke direktori root"
          cp -r dist/* .

          echo "📦 Commit dan push ke branch output"
          git checkout -B output
          git add .
          git commit -m "Update pacman contribution graph - $(date -u +'%Y-%m-%d %H:%M:%S UTC')" || echo "Nothing to commit"

          echo "🔐 Setup remote pakai token"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git

          git push origin output --force
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
